### ISSUE TITLE
Backlog-limit not working.

### ISSUE THREAD

**Issue by johnbritto1** [witem/rtail#1]
Hello,

Appreciate your work. 
For some reason, the --backlog-limit is not working.
I have set backlog limit to 10000, but can view only 100 lines of logs per stream.

r-tail verison 1.0.6
ubuntu 16.04 LTS
nodejs version v8.11.2
npm version 6.0.1

Please advice.

Thanks.

**Comment by usebaz** [comment]
Hi, yes, on front-end display only 100 lines. It be fixed in **v2**.

**Comment by witem** [comment]
Fixed in version: 2.0.0-beta

**Comment by johnbritto1** [comment]
Great.
--
John Britto
DevOps Engineer
Sodexis, Inc.
www.sodexis.com
M: +91-8012186991
<john@sodexis.com>
